//tealium universal tag - utag.196 ut4.0.201809262004, Copyright 2018 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[function(a,b){try{if(1){if(window.isTealiumReady){window.addEventListener("lotame_ready",function(){if(/^((?!support|help|instruction).)*$/.test(window.location.href)){lotame.bcpw("act","Content View");lotame.bcpw("med","Content View: "+document.title);}
if(/.*(support)?\.blurb\..*\/(help|instruction).*/.test(window.location.href)){lotame.bcpw("act","Content View: Help and Support");lotame.bcpw("med","Content View: Help and Support: "+document.title);}
if(typeof(utag.data['customer_id'])!=="undefined"){lotame.bcpw("tp","QYPF","tpid",utag.data['customer_id']);}
if(/.*/.test(window.location.href)){var time=new Date();var hours=time.getHours();var min=time.getMinutes();var day=time.toString().split(' ')[0];var timeBucket='';if(min>=0&&min<30){if(hours==12)timeBucket=12+':'+'00 PM'
else if(hours>=12)timeBucket=(hours-12)+':'+'00 PM'
else timeBucket=hours+':'+'00 AM'}
else if(min>=30&&min<=59){if(hours==12)timeBucket=12+':'+'30 PM'
else if(hours>=12)timeBucket=(hours-12)+':'+'30 PM'
else timeBucket=hours+':'+'30 AM'}
lotame.bcpw("genp","Day: "+day);lotame.bcpw("genp","Time: "+timeBucket);var sessionExist=sessionStorage.getItem('sessionExist');if(sessionExist==null){sessionStorage.setItem('sessionExist','true');var ref=document.referrer;var searchOrganic=ref.match('^https?:\/\/(.*\.|search\.|www\.|ricerca\.)?(google|baidu|bing|aol|yahoo|ask|yandex|dogpile|duckduckgo|naver|haosou|daum|seznam|virgilio).([a-z]+)([\.a-z]{3,5})?/');var socialOrganic=ref.match('^https?:\/\/(www\.)?(blog(ger|spot)\.com|delicious\.com|deviantart\.com|disqus\.com|face(book|faceparty)\.com|fc2\.com|fli(ckr|xster)\.com|foursquare\.com|friend(feed|ster)\.com|hi5\.com|linkedin\.com|livejournal\.com|myspace\.com|photobucket\.com|pinterest\.com|plus\.google\.com|reddit\.com|slideshare\.net|smugmug\.com|stack(overflow|exchange)\.com|stumbleupon\.com|t\.co|tumblr\.com|twitter\.com|vimeo\.com|yelp\.com|youtube\.com)($|\/)');function getParameterByName(name){name=name.replace(/[\[]/,"\\\[").replace(/[\]]/,"\\\]");var regexS="[\\?&]"+name+"=([^&#]*)";var regex=new RegExp(regexS);var results=regex.exec(window.location.search);if(results==null){return"";}
else{return decodeURIComponent(results[1].replace(/\+/g," "));}}
if(location.href.indexOf('utm')>0){var utmSource=getParameterByName('utm_source');var utmMedium=getParameterByName('utm_medium');var utmCampaign=getParameterByName('utm_campaign');var utmContent=getParameterByName('utm_content');var utmTerm=getParameterByName('utm_term');var utmGroup=getParameterByName('utm_group');if(utmSource.length>0)lotame.bcpw('genp','source : '+utmSource);if(utmMedium.length>0)lotame.bcpw('genp','medium : '+utmMedium);if(utmCampaign.length>0)lotame.bcpw('genp','campaign : '+utmCampaign);if(utmContent.length>0)lotame.bcpw('genp','content : '+utmContent);if(utmTerm.length>0)lotame.bcpw('genp','term : '+utmTerm);if(utmGroup.length>0)lotame.bcpw('genp','group : '+utmGroup);}
else if(searchOrganic!=null){lotame.bcpw('genp','source : organic search : '+document.referrer.split('/')[2]);}
else if(socialOrganic!=null){lotame.bcpw('genp','source : organic social : '+document.referrer.split('/')[2]);}
else if(ref==''){lotame.bcpw("genp","source : direct");}
else if(ref.indexOf('blurb')>0){}
else{lotame.bcpw("genp","source : referrer : "+document.referrer.split('/')[2]);}}}
if(/.*bookwright-install.*/.test(window.location.pathname)&&utag.data['dom.query_string'].indexOf('download=true')>0){if(/.*mac(\/)?$/.test(window.location.pathname))
{var BWVrsn='mac';}
else
{var BWVrsn='pc';}
lotame.bcpw("med","Download BookWright: "+BWVrsn);}
if(typeof(utag.data['event_category'])!=='undefined'){if(utag.data['event_category'].indexOf('Modal Tracking')>0){lotame.bcpw("act","Modal Tracking");lotame.bcpw("genp","Modal Tracking: "+document.title);}}
if(/\/b\/\d*-/.test(window.location.pathname)){lotame.bcpw("act","Product View: Bookstore");lotame.bcpw("genp","Product View: Bookstore: Name: "+jQuery('.book-title').text());}
if(/\/my\/checkout\/shipping.*/.test(window.location.pathname)){lotame.bcpw("act","Bookify Checkout");lotame.bcpw("genp","Bookify: Checkout: Page: Shipping");}
if(/\/my\/checkout\/billing.*/.test(window.location.pathname)){lotame.bcpw("act","Bookify: Checkout");lotame.bcpw("genp","Bookify: Checkout: Page: Payment");}
if(typeof(utag.data['order_id'])!=="undefined"){if(typeof(utag.data['cp.hasPurchased'])!=="undefined"){bucketLow=Math.floor(Math.round(parseFloat(utag.data['order_total']))/50);bucketString=""+(bucketLow*50)+" - "+((bucketLow+1)*50);_cc11094.bcpw("genp","Bookify: Purchase: Price Bucket: "+bucketString);if(utag.data['cp.hasPurchased']==1){lotame.bcpw("genp","Order Book: First Purchase");}else{lotame.bcpw("genp","Order Book: Repeat Purchase");}}}});if(/\/my\/account\/register/.test(window.location.pathname)){jQuery('.js-register-form').submit(function(){lotame.bcpw("act","Account Creation");lotame.bcpw("genp","Account Creation: "+document.title);});}
var moduleName="lotame_clicks";var moduleVersion="1.0";_MAT.core.createModule(moduleName,moduleVersion,function(element,edata,event){if(1==0){}
else{if(!element||event.which!=1){edata.skip=true;return;}
else if(element.hasParent('header.header,footer.footer')&&element.is('a')){lotame.bcpw("act","Link Tracking");if(typeof(element.attr('href')!=="undefined")){lotame.bcpw("genp","Current Page:  "+window.location.pathname+" > Destination: "+element.attr('href'));}}else if(element.hasParent('.product-highlight__cta')&&element.is('a.js-photo-books-tool')){lotame.bcpw("act","Book Creation: Create Book With Blurb");}else if(element.hasParent('.product-highlight__cta')&&element.is('a.btn.btn--white-on-black')){lotame.bcpw("act","Book Creation: Create and Upload PDF");}
else if(element.is('.btn--black-on-white.beautiful-modal__form-button')){lotame.bcpw("act","Newsletter Signup");lotame.bcpw("genp","Newsletter Signup: "+document.title);}else if(element.is('#btn-order,a.btn-order-book')){lotame.bcpw("act","Bookify: "+"Buy");lotame.bcpw("genp","Bookify: "+"Buy");}else if(element.is('#btn-sell,a.lnk-print-settings')){lotame.bcpw("act","Bookify: "+"Sell");lotame.bcpw("genp","Bookify: "+"Sell");}else if(element.is('#add-to-cart-btn')){lotame.bcpw("act","Bookify: Add to Cart");}else if(element.is('#add-to-cart-button')&&/\/b\/\d*-/.test(window.location.pathname)){lotame.bcpw("act","Add to Cart: Bookstore");lotame.bcpw("genp","Add to Cart: Bookstore: Name: "+jQuery('.book-title').cText());}else if(element.is('#shipping_form .ship_method .to_disable')){lotame.bcpw("act","Bookify: Shipping Method");lotame.bcpw("genp","Bookify: Shipping Method: "+element.hasParent('.ship_method',true).find('label').cText());}else if((element.hasParent('.dynamic-content__link')||element.is('.cta-banner__btn--cta'))&&/\/mobile.*/.test(window.location.pathname)){lotame.bcpw("act","App Store Click");lotame.bcpw("med","App Store Click: "+document.title);}
else{edata.skip=true;return;};}
return edata.skip?"":element.attr(_MAT.config.tracker_attribute,'track')});}}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={"id":"LOTCC_11094","base_url":"//tags.crwdcntrl.net/c/11094/cc.js?ns=_cc11094"
};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
u.loader_cb=function(){u.initialized=true;window.lotame=window['_cc11094'];lotame.bcp();lotame.bcpw("sm",location.pathname);lotame.ready=true;var lotameEvent=new Event("lotame_ready");window.dispatchEvent(lotameEvent);};if(!u.initialized){u.loader({"type":"script","src":u.data.base_url,"cb":u.loader_cb,"loc":"script","id":u.data.id});}else{u.loader_cb();}
}};utag.o[loader].loader.LOAD(id);})("196","blurb.main");}catch(error){utag.DB(error);}
