//tealium universal tag - utag.444 ut4.0.201811162016, Copyright 2018 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
u.encode=function(a,b){b="";try{b=encodeURIComponent(a)}catch(e){utag.DB(e);}if(b==""){b=escape(a);}return b}
u.ev={"view":1};u.scriptrequested=false;u.rp=function(a,b){if(typeof a!=="undefined"&&a.indexOf("@@")>0){a=a.replace(/@@([^@]+)@@/g,function(m,d){if(b[d]){return u.encode(b[d]);}else{return"";}});}
return a;};u.map={};u.extend=[function(a,b){try{if((b['dom.url'].toString().toLowerCase().indexOf('br.blurb.com'.toLowerCase())<0&&b['dom.url'].toString().toLowerCase().indexOf('/blog/'.toLowerCase())<0)){function gtag(){dataLayer.push(arguments);}
gtag('js',new Date());gtag('config','AW-1061326981');gtag('event','conversion',{'send_to':'AW-1061326981/dHlBCNellwcQhaGK-gM','pagetype':'other'});}}catch(e){utag.DB(e)}},function(a,b){try{if(b['event_name'].toString().indexOf('large_order_form_submit')>-1){function gtag(){dataLayer.push(arguments);}
gtag('js',new Date());gtag('config','AW-1061326981');gtag('event','conversion',{'send_to':'AW-1061326981/wUIVCPXY1X4QhaGK-gM','pagetype':'conversion'});}}catch(e){utag.DB(e)}},function(a,b){try{if(b['event_name'].toString().indexOf('promote_public')>-1){function gtag(){dataLayer.push(arguments);}
gtag('js',new Date());gtag('config','AW-1061326981');gtag('event','conversion',{'send_to':'AW-1061326981/4jzrCO-5_G8QhaGK-gM','pagetype':'conversion'});}}catch(e){utag.DB(e)}},function(a,b){try{if(b['event_name']=='promote_public'){function gtag(){dataLayer.push(arguments);}
gtag('js',new Date());gtag('config','AW-1061326981');gtag('event','conversion',{'send_to':'AW-1061326981/J91TCLWeym8QhaGK-gM','pagetype':'conversion'});}}catch(e){utag.DB(e)}},function(a,b){try{if(b['event_name']=='promote_invite'){function gtag(){dataLayer.push(arguments);}
gtag('js',new Date());gtag('config','AW-1061326981');gtag('event','conversion',{'send_to':'AW-1061326981/_90ICPLH-28QhaGK-gM','pagetype':'conversion'});}}catch(e){utag.DB(e)}},function(a,b){try{if((typeof b['order_id']!='undefined'&&/(www|au|it|br|nl|la|fr)\.blurb\.(com|co\.uk|fr|de|es|ca)\/my\/checkout\/order_complete\/?/.test(b['dom.url'])&&typeof b['js_page.tmParamExtras.isNAP']!='undefined'&&b['js_page.tmParamExtras.isNAP']=='0'&&b['cp.hasPurchased']=='1')){function gtag(){dataLayer.push(arguments);}
gtag('js',new Date());gtag('config','AW-1061326981');gtag('event','purchase',{'send_to':'AW-1061326981/vuWmCPr8nG0QhaGK-gM','pagetype':'purchase','value':b['order_total'],'currency':'USD','transaction_id':utag.data.order_id.replace(/\D/g,'')});}}catch(e){utag.DB(e)}},function(a,b){try{if((/dom.urlREGULAR_EXPRESSION(www|au|it|br|nl|la|fr)\.blurb\.(com|co\.uk|fr|de|es|ca)\/my\/checkout\/order_complete\/?/.test(b['dom.url'])&&typeof b['js_page.tmParamExtras.isNAP']!='undefined'&&b['js_page.tmParamExtras.isNAP']=='1')){function gtag(){dataLayer.push(arguments);}
gtag('js',new Date());gtag('config','AW-1061326981');gtag('event','purchase',{'send_to':'AW-1061326981/RmcoCNz_h3AQhaGK-gM','pagetype':'purchase','value':b['order_total'],'currency':'USD','transaction_id':utag.data.order_id.replace(/\D/g,'')});}}catch(e){utag.DB(e)}},function(a,b){try{if((typeof b['cp.new_reg']!='undefined'&&b['cp.new_reg']=='true')){function gtag(){dataLayer.push(arguments);}
gtag('js',new Date());gtag('config','AW-1061326981');gtag('event','conversion',{'send_to':'AW-1061326981/signup','pagetype':'conversion','value':1,'aw_feed_language':b['customer_language']});}}catch(e){utag.DB(e)}},function(a,b){try{if((parseFloat(b['cp.hasPurchased'])>parseFloat(1)&&/(www|au|it|br|nl|la|fr)\.blurb\.(com|co\.uk|fr|de|es|ca)\/my\/checkout\/order_complete\/?/.test(b['dom.url'])&&typeof b['js_page.tmParamExtras.isNAP']!='undefined'&&b['js_page.tmParamExtras.isNAP']=='0'&&typeof b['order_id']!='undefined')){function gtag(){dataLayer.push(arguments);}
gtag('js',new Date());gtag('config','AW-1061326981');gtag('event','purchase',{'send_to':'AW-1061326981/WGz8CK7RzGQQhaGK-gM','pagetype':'purchase','value':b['order_total'],'currency':'USD','transaction_id':utag.data.order_id.replace(/\D/g,'')});}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f;u.data={"qsp_delim":"&"||"&","kvp_delim":"="||"=","qs_delim":"?"||"?","tag_type":"script","base_url":"https://www.googletagmanager.com/gtag/js","secure_base_url":"","static_params":"id=AW-1061326981","cachebust":"disabled","cachevar":""||"_rnd","requestscriptonce":"enabled"};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};utag.DB("send:444:EXTENSIONS");utag.DB(b);c=[];for(d in utag.loader.GV(u.map)){if(typeof b[d]!=="undefined"&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(!u.data.hasOwnProperty(e[f])){c.push(e[f]+"##kvp_delim##"+u.encode(b[d]));}
u.data[e[f]]=b[d];}}}
if(!u.data.base_url){if(!u.data.secure_base_url){utag.DB("Error: No Base URL or Secure HTTPS Override Provided.");return;}else{u.data.base_url=u.data.secure_base_url;utag.DB("No Base URL provided, using Secure HTTPS Override.");}}
u.data.secure_base_url=u.data.secure_base_url||u.data.base_url;u.data.url=(location.protocol==="https:"?u.data.secure_base_url:u.data.base_url);if(u.data.url.indexOf("http")!==0&&u.data.url.indexOf("/")!==0){u.data.url=location.protocol+"//"+u.data.url;}
if(u.data.static_params){c.push(u.data.static_params);}
var cb_check=new RegExp("(\\"+u.data.qs_delim+"|"+u.data.qsp_delim+")"+u.data.cachevar+"=");if(u.data.cachebust==="enabled"&&!cb_check.test(u.data.url)){c.push([u.data.cachevar,Math.random()].join(u.data.kvp_delim));}
if(c.length>0){if(u.data.url.indexOf(u.data.qs_delim)<0){u.data.url+=u.data.qs_delim;}else if(u.data.url.indexOf(u.data.qs_delim)!==(u.data.url.length-1)){u.data.url+=u.data.qsp_delim;}}
u.data.url=u.rp(u.data.url,b)+u.rp(c.join(u.data.qsp_delim),b);u.data.url=u.data.url.replace(/##kvp_delim##/g,u.data.kvp_delim);u.callback=u.callback||function(){};if(u.data.requestscriptonce==="enabled"&&u.data.tag_type==="script"){if(!u.scriptrequested){u.scriptrequested=true;u.loader({"type":u.data.tag_type,"src":u.data.url,"loc":"script","id":"utag_444","cb":u.callback});}else{u.callback();}}else{u.loader({"type":u.data.tag_type,"src":u.data.url,"loc":"script","id":"utag_444","cb":u.callback});}
utag.DB("send:444:COMPLETE");}};utag.o[loader].loader.LOAD(id);}("444","blurb.main"));}catch(error){utag.DB(error);}
